# Day 3 - NumPy Basics

**AI & Machine Learning Internship**

**Author:** Neethu Suresh

## Topics Covered

- Introduction to NumPy
- Creating Arrays
- Array Attributes
- Array Operations
- Mathematical Functions

In [2]:
import numpy as np

## Creating NumPy Arrays

In [3]:
array1 = np.array([10, 20, 30, 40, 50])

print("Array:")
print(array1)

Array:
[10 20 30 40 50]


## Two-Dimensional Array

In [4]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(array2)

[[1 2 3]
 [4 5 6]]


## Array Attributes

In [5]:
print("Shape:", array2.shape)
print("Dimensions:", array2.ndim)
print("Data Type:", array2.dtype)
print("Size:", array2.size)

Shape: (2, 3)
Dimensions: 2
Data Type: int64
Size: 6


## Array Operations

In [6]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


## Mathematical Functions

In [7]:
numbers = np.array([5, 10, 15, 20])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 50
Mean: 12.5
Maximum: 20
Minimum: 5


## Creating Special Arrays

In [8]:
print("Zeros Array")
print(np.zeros((2,3)))

print()

print("Ones Array")
print(np.ones((2,3)))

print()

print("Identity Matrix")
print(np.eye(3))

Zeros Array
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Conclusion

NumPy provides powerful tools for working with numerical data efficiently. It is widely used in Data Science, Machine Learning, and Artificial Intelligence.